import gdiplus,\
	GdiplusStartup,'GdiplusStartup',\
	GdipLoadImageFromStream,'GdipLoadImageFromStream',\
	GetImageEncodersSize,'GetImageEncodersSize',\
	GetImageEncoders,' GetImageEncoders',\
	GdipSaveImageToFile,'GdipSaveImageToFile',\
	GdiplusShutdown,'GdiplusShutdown',\
	GdipCreateBitmapFromStream,'GdipCreateBitmapFromStream',\
	GdipDisposeImage,'GdipDisposeImage',\
	GdipCreateFromHWND,'GdipCreateFromHWND',\
	GdipDrawImageRectRectI,'GdipDrawImageRectRectI',\
	GdipCreateBitmapFromGraphics,'GdipCreateBitmapFromGraphics',\
	GdipCreateHBITMAPFromBitmap,'GdipCreateHBITMAPFromBitmap',\
	GdipCreateFromHDC,'GdipCreateFromHDC'