import gdiplus,\
	GdiplusStartup,'GdiplusStartup',\
	GdipLoadImageFromStream,'GdipLoadImageFromStream',\
	GetImageEncodersSize,'GetImageEncodersSize',\
	GetImageEncoders,' GetImageEncoders',\
	GdipSaveImageToFile,'GdipSaveImageToFile',\
	GdiplusShutdown,'GdiplusShutdown',\
	GdipCreateBitmapFromStream,'GdipCreateBitmapFromStream',\
	GdipDisposeImage,'GdipDisposeImage',\
	GdipCreateFromHWND,'GdipCreateFromHWND',\
	GdipDrawImageRectRectI,'GdipDrawImageRectRectI',\
	GdipCreateBitmapFromGraphics,'GdipCreateBitmapFromGraphics',\
	GdipCreateHBITMAPFromBitmap,'GdipCreateHBITMAPFromBitmap',\
	GdipCreateFromHDC,'GdipCreateFromHDC',\
	GdipDrawImage,'GdipDrawImage',\
	GdipDrawImageRect,'GdipDrawImageRect',\
	GdipGetImageHeight,'GdipGetImageHeight',\
	GdipGetImageWidth,'GdipGetImageWidth',\
	GdipDrawImageI,'GdipDrawImageI',\
	GdipDeleteGraphics,'GdipDeleteGraphics',\
	GdipCreateSolidFill,'GdipCreateSolidFill',\
	GdipFillRectangle,'GdipFillRectangle',\
	GdipDeleteBrush,'GdipDeleteBrush',\
	GdipCloneImage,'GdipCloneImage',\
	GdipGraphicsClear,'GdipGraphicsClear',\
	GdipGetImageGraphicsContext,'GdipGetImageGraphicsContext'