
; WININET API calls
	      
import wininet,\
	InternetOpenA,'InternetOpenA',\
	InternetReadFile,'InternetReadFile',\
	InternetOpenUrlA,'InternetOpenUrlA',\
	InternetCloseHandle,'InternetCloseHandle',\
	InternetConnectA,'InternetConnectA',\
	HttpEndRequestA,'HttpEndRequestA',\
	HttpSendRequestA,'HttpSendRequestA',\
	HttpOpenRequestA,'HttpOpenRequestA',\
	InternetQueryDataAvailable,'InternetQueryDataAvailable',\
	InternetSetOptionA,'InternetSetOptionA',\
	InternetQueryOptionA,'InternetQueryOptionA',\
	InternetSetCookieA,'InternetSetCookieA',\
	InternetGetCookieA,'InternetGetCookieA',\
	InternetCrackUrlA,'InternetCrackUrlA',\
	HttpQueryInfoA,'HttpQueryInfoA',\
	HTTPopenRequestA,'HTTPopenRequestA',\
	FtpPutFileA,'FtpPutFileA',\
	FtpPutFileW,'FtpPutFileW'