
; WINMM API calls
	      
import winmm,\
	PlaySoundW,'PlaySoundW',\
	PlaySoundA,'PlaySoundA',\
	waveOutGetPosition,'waveOutGetPosition',\
	waveOutOpen,'waveOutOpen',\
	waveOutPrepareHeader,'waveOutPrepareHeader',\
	waveOutReset,'waveOutReset',\
	waveOutUnprepareHeader,'waveOutUnprepareHeader',\
	waveOutWrite,'waveOutWrite',\
	waveOutClose,'waveOutClose',\
	waveInOpen,'waveInOpen',\
	waveInPrepareHeader,'waveInPrepareHeader',\
	waveInAddBuffer,'waveInAddBuffer',\
	waveInStart,'waveInStart',\
	waveInUnprepareHeader,'waveInUnprepareHeader',\
	waveInClose,'waveInClose',\
	waveOutSetVolume,'waveOutSetVolume',\
	waveInStop,'waveInStop'
